### ISSUE TITLE
Neopixel strip demo not working

### ISSUE THREAD

**Issue by ThePixelDeveloper** [wokwi/wokwi-playgrounds#1]
Trying to see the Neopixel strip demo in action and can't get it to work with the code that's there: https://wokwi.com/playground/neopixel-strip 

I've tried in Brave and Safari. The other demo (using FastLED) seems to work, I wonder if it's a problem with the Neopixel library?

**Comment by urish** [comment]
Thanks for reporting, fixed!

**Comment by ThePixelDeveloper** [comment]
That's rapid @urish 

Impressed, thanks a lot 👍🏻

**Comment by urish** [comment]
Excellent :-) 

p.s. if you do something, feel free to share
